# Generated by Django 2.1.12 on 2019-10-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_shot',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
